const columnMappings = {
  batterBasic: {
      Player: 'Player',
      Team: 'Team',
      Position: 'Position',
      year: 'Year',
      player_age: 'Age',
      ab: 'AB',
      pa: 'PA',
      hit: 'Hits',
      single: 'Singles',
      double: 'Doubles',
      triple: 'Triples',
      home_run: 'HR',
      strikeout: 'SO',
      walk: 'Walks',
      batting_avg: 'BA',
      slg_percent: 'SLG',
      on_base_percent: 'OBP',
      on_base_plus_slg: 'OPS',
      b_rbi: 'RBI',
      r_total_stolen_base: 'SB',
      b_hit_by_pitch: 'HBP'
  },
  batterStatcast: {
      Player: 'Player',
      Team: 'Team',
      Position: 'Position',
      year: 'Year',
      player_age: 'Age',
      k_percent: 'K%',
      bb_percent: 'BB%',
      xba: 'xBA',
      xslg: 'xSLG',
      woba: 'wOBA',
      xwoba: 'xWOBA',
      xobp: 'xOBP',
      xiso: 'xISO',
      exit_velocity_avg: 'Avg EV',
      launch_angle_avg: 'Avg LA',
      sweet_spot_percent: 'Sweet Spot%',
      barrel_batted_rate: 'Barrel Rate',
      hard_hit_percent: 'Hard Hit%',
      avg_best_speed: 'Avg Best Speed',
      avg_hyper_speed: 'Avg Hyper Speed',
      whiff_percent: 'Whiff%',
      swing_percent: 'Swing%'
  },
  batter: {},
  pitcher: {
      Player: 'Player',
      Team: 'Team',
      Position: 'Position',
      year: 'Year',
      player_age: 'Age',
      p_game: 'Games',
      p_formatted_ip: 'IP',
      pa: 'PA',
      ab: 'AB',
      hit: 'Hits',
      single: 'Singles',
      double: 'Doubles',
      triples: 'Triples',
      home_run: 'HR',
      strikeout: 'SO',
      walks: 'Walks',
      k_percent: 'K%',
      bb_percent: 'BB%',
      batting_avg: 'BA',
      slg_percent: 'SLG',
      on_base_percent: 'OBP',
      on_base_plus_slg: 'OPS',
      p_earned_run: 'ER',
      p_win: 'W',
      p_loss: 'L',
      p_era: 'ERA',
      p_quality_start: 'QS',
      xba: 'xBA',
      xslg: 'xSLG',
      woba: 'WOBA',
      xwoba: 'xWOBA',
      bacon: 'BACON',
      xbacon: 'xBACON',
      exit_velocity_avg: 'Avg EV',
      launch_angle_avg: 'Avg LA',
      barrel_batted_rate: 'Barrel Rate',
      avg_hyper_speed: 'Avg Hyper Speed',
      z_swing_percent: 'Swing %',
      z_swing_percent: 'Miss %',
      z_swing_percent: 'Out of Zone Swing %',
      oz_swing_miss_percent: 'Out of Zone Miss %',
      out_zone_percent: 'Out of Zone %'
  }
};

Object.assign(columnMappings.batter, columnMappings.batterBasic, columnMappings.batterStatcast, columnMappings.pitcher);

  const tableMappings = {
    batterBasic: 'Basic Batting Stats',
    batterStatcast: 'Statcast Batting Stats',
    batter: 'Batting Stats',
    pitcher: 'Pitcher Stats'
  };
  
  export { columnMappings, tableMappings };
  