const columnMappings = {
    batter : {
    Player: 'Player',
    player_id: 'Player ID',
    year: 'Year',
    Team: 'Team',
    Pos: 'Position',
    player_age: 'Age',
    ab: 'AB',
    pa: 'PA',
    hit: 'Hits',
    single: 'Singles',
    double: 'Doubles',
    triple: 'Triples',
    home_run: 'HR',
    strikeout: 'SO',
    walk: 'Walks',
    batting_avg: 'BA',
    slg_percent: 'SLG',
    on_base_percent: 'OBP',
    on_base_plus_slg: 'OPS',
    b_rbi: 'RBI',
    r_total_stolen_base: 'SB',
    b_hit_by_pitch: 'HBP',
    player_id_x: 'Player ID X',
    k_percent: 'K%',
    bb_percent: 'BB%',
    xba: 'xBA',
    xslg: 'xSLG',
    woba: 'wOBA',
    xwoba: 'xWOBA',
    xobp: 'xOBP',
    xiso: 'xISO',
    exit_velocity_avg: 'Exit Velocity Avg',
    launch_angle_avg: 'Launch Angle Avg',
    sweet_spot_percent: 'Sweet Spot%',
    barrel_batted_rate: 'Barrel Batted Rate',
    hard_hit_percent: 'Hard Hit%',
    avg_best_speed: 'Avg Best Speed',
    avg_hyper_speed: 'Avg Hyper Speed',
    whiff_percent: 'Whiff%',
    swing_percent: 'Swing%',
    composite_hit_metric: 'Composite Hit Metric'
    },

  pitcher: {
    Player: 'Player',
    player_id: 'Player ID',
    year: 'Year',
    player_age: 'Age',
    Team: 'Team',
    p_game: 'Games',
    p_formatted_ip: 'Innings Pitched',
    pa: 'Plate Appearances',
    ab: 'At Bats',
    hit: 'Hits',
    single: 'Singles',
    double: 'Doubles',
    triple: 'Triples',
    home_run: 'Home Runs',
    strikeout: 'Strikeouts',
    walk: 'Walks',
    k_percent: 'K%',
    bb_percent: 'BB%',
    batting_avg: 'Batting Average',
    slg_percent: 'Slugging Percentage',
    on_base_percent: 'On-Base Percentage',
    on_base_plus_slg: 'On-Base Plus Slugging',
    p_earned_run: 'Earned Runs',
    p_win: 'Wins',
    p_loss: 'Losses',
    p_era: 'ERA',
    p_opp_batting_avg: 'Opponent Batting Average',
    p_quality_start: 'Quality Starts',
    xba: 'xBA',
    xslg: 'xSLG',
    woba: 'wOBA',
    xwoba: 'xWOBA',
    bacon: 'BACON',
    xbacon: 'xBAcon',
    exit_velocity_avg: 'Exit Velocity Avg',
    launch_angle_avg: 'Launch Angle Avg',
    barrel_batted_rate: 'Barrel Batted Rate',
    avg_hyper_speed: 'Avg Hyper Speed',
    z_swing_percent: 'Z-Swing%',
    z_swing_miss_percent: 'Z-Swing Miss%',
    oz_swing_percent: 'OZ-Swing%',
    oz_swing_miss_percent: 'OZ-Swing Miss%',
    out_zone_percent: 'Out Zone%',
    composite_pitcher_metric: 'Composite Pitcher Metric'
  }
};

Object.assign(columnMappings.batter, columnMappings.pitcher);

  const tableMappings = {
    batter: 'Batting Stats',
    pitcher: 'Pitcher Stats'
  };
  
  export { columnMappings, tableMappings };
  